-- MySQL Script generated by MySQL Workbench
-- Mon Nov 17 03:06:59 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`WorkoutDetails`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`WorkoutDetails` ;

CREATE TABLE IF NOT EXISTS `mydb`.`WorkoutDetails` (
  `DetailID` INT NULL AUTO_INCREMENT,
  `SessionID` INT NOT NULL,
  `ExerciseID` INT NOT NULL,
  `Sets` INT NULL,
  `Reps` INT NULL,
  `Weight` DECIMAL(6,2) NULL,
  `RestTime` INT NULL,
  `Notes` TEXT NULL,
  PRIMARY KEY (`DetailID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`WorkoutSessions`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`WorkoutSessions` ;

CREATE TABLE IF NOT EXISTS `mydb`.`WorkoutSessions` (
  `SessionID` INT NOT NULL AUTO_INCREMENT,
  `UserID` INT NOT NULL,
  `SessionDate` DATE NOT NULL,
  `WorkoutType` VARCHAR(50) NULL,
  `TotalDuration` INT NULL,
  `TotalCaloriesBurned` INT NULL,
  `Notes` TEXT NULL,
  `WorkoutDetails_DetailID` INT NOT NULL,
  PRIMARY KEY (`SessionID`),
  UNIQUE INDEX `SessionID_UNIQUE` (`SessionID` ASC) VISIBLE,
  INDEX `fk_WorkoutSessions_WorkoutDetails1_idx` (`WorkoutDetails_DetailID` ASC) VISIBLE,
  CONSTRAINT `fk_WorkoutSessions_WorkoutDetails1`
    FOREIGN KEY (`WorkoutDetails_DetailID`)
    REFERENCES `mydb`.`WorkoutDetails` (`DetailID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`NutritionLog`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`NutritionLog` ;

CREATE TABLE IF NOT EXISTS `mydb`.`NutritionLog` (
  `LogID` INT NOT NULL AUTO_INCREMENT,
  `UserID` INT NOT NULL,
  `LogDate` DATE NOT NULL,
  `MealType` VARCHAR(50) NULL,
  `FoodItem` VARCHAR(100) NOT NULL,
  `Calories` INT NOT NULL,
  `Protein` DECIMAL(6,2) NULL,
  `Carbs` DECIMAL(6,2) NULL,
  `Fats` DECIMAL(6,2) NULL,
  `ServingSize` VARCHAR(50) NULL,
  PRIMARY KEY (`LogID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`BodyMeasurements`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`BodyMeasurements` ;

CREATE TABLE IF NOT EXISTS `mydb`.`BodyMeasurements` (
  `MeasurementID` INT NULL AUTO_INCREMENT,
  `UserID` INT NOT NULL,
  `MeasurementDate` DATE NOT NULL,
  `Weight` DECIMAL(5,2) NULL,
  `BodyFatPercentage` DECIMAL(4,2) NULL,
  `Chest` DECIMAL(5,2) NULL,
  `Waist` DECIMAL(5,2) NULL,
  `Arms` DECIMAL(5,2) NULL,
  `Thighs` DECIMAL(5,2) NULL,
  PRIMARY KEY (`MeasurementID`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Users`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Users` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Users` (
  `UserID` INT NOT NULL AUTO_INCREMENT,
  `FirstName` VARCHAR(50) NOT NULL,
  `LastName` VARCHAR(50) NOT NULL,
  `Email` VARCHAR(100) NOT NULL,
  `BirthDate` DATE NULL,
  `Gender` VARCHAR(10) NULL,
  `Height` DECIMAL(5,2) NULL,
  `FitnessGoals` TEXT NULL,
  `CreatedDate` TIMESTAMP NULL,
  `WorkoutSessions_SessionID` INT NOT NULL,
  `NutritionLog_LogID` INT NOT NULL,
  `BodyMeasurements_MeasurementID` INT NOT NULL,
  PRIMARY KEY (`UserID`),
  UNIQUE INDEX `UserID_UNIQUE` (`UserID` ASC) VISIBLE,
  UNIQUE INDEX `Email_UNIQUE` (`Email` ASC) VISIBLE,
  INDEX `fk_Users_WorkoutSessions_idx` (`WorkoutSessions_SessionID` ASC) VISIBLE,
  INDEX `fk_Users_NutritionLog1_idx` (`NutritionLog_LogID` ASC) VISIBLE,
  INDEX `fk_Users_BodyMeasurements1_idx` (`BodyMeasurements_MeasurementID` ASC) VISIBLE,
  CONSTRAINT `fk_Users_WorkoutSessions`
    FOREIGN KEY (`WorkoutSessions_SessionID`)
    REFERENCES `mydb`.`WorkoutSessions` (`SessionID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Users_NutritionLog1`
    FOREIGN KEY (`NutritionLog_LogID`)
    REFERENCES `mydb`.`NutritionLog` (`LogID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Users_BodyMeasurements1`
    FOREIGN KEY (`BodyMeasurements_MeasurementID`)
    REFERENCES `mydb`.`BodyMeasurements` (`MeasurementID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Exercise`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Exercise` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Exercise` (
  `ExerciseID` INT NOT NULL AUTO_INCREMENT,
  `ExerciseName` VARCHAR(100) NOT NULL,
  `MuscleGroup` VARCHAR(50) NULL,
  `Equipment` VARCHAR(100) NULL,
  `DifficultyLevel` VARCHAR(20) NULL,
  `Description` TEXT NULL,
  `WorkoutDetails_DetailID` INT NOT NULL,
  PRIMARY KEY (`ExerciseID`),
  UNIQUE INDEX `ExerciseID_UNIQUE` (`ExerciseID` ASC) VISIBLE,
  INDEX `fk_Exercise_WorkoutDetails1_idx` (`WorkoutDetails_DetailID` ASC) VISIBLE,
  CONSTRAINT `fk_Exercise_WorkoutDetails1`
    FOREIGN KEY (`WorkoutDetails_DetailID`)
    REFERENCES `mydb`.`WorkoutDetails` (`DetailID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
